### ISSUE TITLE
Workflow for dfont generation

### ISSUE THREAD

**Issue by nirajd** [trippyroman/tamsyn-mac-version#1]
Hi,
Can you share your workflow (tools included) to generate dfont from bitmap fonts? Sometimes I find bitmap fonts I'd like to use that don't have a format for macs and have to just give up.
Thanks!

**Comment by roman0x58** [comment]
Hi, I used [FontForge](https://fontforge.github.io/en-US/downloads/mac/) for mac, and just export bitmap fonts as dfont.  You can check `sfd` files from this repository to take a look which settings I set.
